base_risk_score_inputs:
  field_ids:
    - 31
    - 21003
    - 30690
    - 30760
    - 4080 # BP automated reading
    - 93 # BP manual reading
    - 20116
    - 2443
  features:
    - BP_medication
additional_risk_score_inputs_aha_acc:
  field_ids:
    - 21000 # ethnic background
additional_risk_score_inputs_prevent:
  field_ids:
    - 21001 # BMI
  features:
    - Cholesterol_medication
    - eGFR
diabetes:
  field_ids:
    - 2443 # diabetes diagnosed by doctor
    - 2976 # age diabetes diagnosed
    - 4041
    - 10844
    # - 2986 # not available
    - 5901
    - 26283
    - 26284
    - 26285
    - 26286
  features:
    - Diabetes_medication
polygenic_risk_scores_all:
  field_ids:
    - 26202
    - 26204
    - 26206
    - 26210
    - 26212
    - 26214
    - 26216
    - 26218
    - 26220
    - 26223
    - 26225
    - 26227
    - 26229
    - 26232
    - 26234
    - 26238
    - 26240
    - 26242
    - 26244
    - 26246
    - 26248
    - 26250
    - 26252
    - 26254
    - 26258
    - 26260
    - 26265
    - 26267
    - 26269
    - 26273
    - 26275
    - 26278
    - 26283
    - 26285
    - 26287
    - 26289
medical_history_all:
  field_ids:
    - 2178
    - 2188
    - 2296
    - 2306
    - 2316
    - 4717
    - 2345
    - 2355
    - 2365
    - 3809
    - 2415
    - 2844
    - 2443
    - 2453
    - 2463
    - 2473
    - 2966
    - 2976
    - 3005
    # - 3627 # Age angina diagnosed
    - 3761
    - 3786
    # - 3894 # Age heart attack diagnosed
    - 3992
    - 4012
    - 4022
    - 4041
    # - 4056 # Age stroke diagnosed
    - 6150 # Vascular/heart problems diagnosed by doctor (participants with CVD values in these fields are anyways filtered out)
    - 6151
    - 6152
    - 2492
    - 6153
    - 6154
    - 6155
    - 6177
    - 6179
blood_samples:
  field_ids:
    - 30000
    - 30010
    - 30020
    - 30030
    - 30040
    - 30050
    - 30060
    - 30070
    - 30080
    - 30090
    - 30100
    - 30110
    - 30120
    - 30130
    - 30140
    - 30150
    - 30160
    - 30600
    - 30610
    - 30620
    - 30630
    - 30640
    - 30650
    - 30660
    - 30670
    - 30680
    - 30690
    - 30700
    - 30710
    - 30720
    - 30730
    - 30740
    - 30750
    - 23000
    - 30760
    - 30770
    - 30780
    - 30790
    - 30810
    - 30840
    - 30860
    - 30870
    - 30880
    - 30890
icd_codes:
  features:
    - ICD_10
    - ICD_9
family_history:
  field_ids:
    - 1807
    - 1845
    - 3526
    - 4501
    - 20107
    - 20110
    - 20111
    - 20112
    - 20113
    - 20114
physical_activity:
  field_ids:
    - 864
    - 874
    - 884
    - 894
    - 904
    - 914
    - 924
    - 943
    - 971
    - 981
    - 991
    - 1001
    - 1011
    - 1021
    - 1070
    - 1080
    - 1090
    - 2624
    - 2634
    - 3637
    - 3647
    - 6162
    - 6164
    - 22032
    - 22033
    - 22034
    - 22035
    - 22036
    - 22037
    - 22038
    - 22039
sleep:
  field_ids:
    - 1160
    - 1190
    - 1200
    - 1210
    - 1220
smoking:
  field_ids:
    - 20116
    - 20160
    - 20161
    - 20162
    - 1239
    - 1249
    - 1259
    - 1269
    - 1279
    - 2644
    - 2867
    - 2887
    - 2897
    - 2907
    - 2926
    - 3436
    - 3456
    - 3466
    - 3506
    - 5959
alcohol:
  field_ids:
    - 20117
    - 1558
    - 1568
    - 1578
    - 1588
    - 1598
    - 1608
    - 1618
    - 1628
    - 3731
lifestyle_and_environment:
  field_ids:
    - 864
    - 874
    - 884
    - 894
    - 904
    - 914
    - 924
    - 943
    - 971
    - 981
    - 991
    - 1001
    - 1011
    - 1021
    - 1070
    - 1080
    - 1090
    - 2624
    - 2634
    - 3637
    - 3647
    - 22035
    - 22036
    - 22037
    - 22038
    - 22039
    - 1160
    - 1190
    - 1200
    - 1210
    - 1220
    - 1239
    - 1249
    - 1259
    - 1269
    - 1279
    - 20116
    - 20160
    - 20161
    - 20162
    - 1558
    - 1568
    - 1578
    - 1588
    - 1598
    - 1608
    - 1618
    - 1628
    - 20117
physical_measures:
  field_ids:
    - 21001
    - 23098
    - 23099
    - 23100
    - 23101
    - 23102
    - 4194
    - 4195
    - 4196
    - 4198
    - 4199
    - 4200
    - 4204
    - 4207
    - 21021
    - 3062
    - 3063
    - 3064
    - 20150
    - 20151
    - 20256
    - 20257
    - 20258
    - 5983
    - 6015
    - 6016
    - 6017
    - 6032
    - 6033
    - 6034
    - 6039
sociodemographics:
  field_ids:
    - 670
    - 709
    - 728
    - 738
    - 767
    - 777
    - 796
    - 6143
    - 845
    - 4674
    - 6138
    - 20119
    - 806
    - 816
    - 826
    - 3426
  features:
    - highest_qualification
urine_assays:
  field_ids:
    - 30510
    - 30500
    - 30505
    - 30520
    - 30525
    - 30530
    - 30535
selected_features_top_10:
  field_ids:
    - 21003
    - 4080
    - 26223
    - 26227
    - 30600
    - 30630
    - 30640
    - 30720
    - 30780
    - 20161
selected_features_top_100:
  features:
    - ICD_10
    - eGFR
  field_ids:
    - 21003
    - 30690
    - 30760
    - 4080
    - 21001
    - 2976
    - 26285
    - 26206
    - 26210
    - 26212
    - 26214
    - 26218
    - 26220
    - 26223
    - 26227
    - 26229
    - 26232
    - 26238
    - 26240
    - 26244
    - 26246
    - 26248
    - 26254
    - 26260
    - 26265
    - 26267
    - 26269
    - 26273
    - 26275
    - 26287
    - 26289
    - 6154
    - 30000
    - 30010
    - 30020
    - 30040
    - 30050
    - 30060
    - 30070
    - 30080
    - 30090
    - 30100
    - 30110
    - 30120
    - 30130
    - 30140
    - 30600
    - 30610
    - 30620
    - 30630
    - 30640
    - 30650
    - 30660
    - 30670
    - 30680
    - 30700
    - 30710
    - 30720
    - 30730
    - 30740
    - 30750
    - 30770
    - 30780
    - 30790
    - 30810
    - 30840
    - 30860
    - 30870
    - 30880
    - 30890
    - 1807
    - 1845
    - 3526
    - 20107
    - 20110
    - 20161
    - 20162
    - 1269
    - 1588
    - 23098
    - 23099
    - 23100
    - 23101
    - 23102
    - 3062
    - 3063
    - 3064
    - 20150
    - 20151
    - 20256
    - 20257
    - 20258
    - 767
    - 30510
    - 30500
    - 30520
    - 30530
selected_features_top_50:
  features:
    - ICD_10
    - eGFR
  field_ids:
    - 21003
    - 30760
    - 4080
    - 26206
    - 26212
    - 26223
    - 26227
    - 26244
    - 26275
    - 26289
    - 30000
    - 30040
    - 30070
    - 30090
    - 30100
    - 30130
    - 30600
    - 30610
    - 30620
    - 30630
    - 30640
    - 30670
    - 30700
    - 30710
    - 30720
    - 30730
    - 30750
    - 30780
    - 30790
    - 30810
    - 30860
    - 30870
    - 30890
    - 1807
    - 1845
    - 3526
    - 20161
    - 23098
    - 23099
    - 23100
    - 23101
    - 23102
    - 3063
    - 3064
    - 20256
    - 20257
    - 30500
    - 30530
