condor:
  request_cpus: 4
  request_memory: 100000
  memory_gpus: 51000
  request_gpus: 1
  bid: 16
data:
  path: "prompt_parts/ukb_2024_02/prompt_parts.parquet"
  split: "config/splits/split_2025_02_17_test_100000.json"
  subset: "subsets/ukb_2024_02/MACE_ADO_no_previous_target.json"
  eval_subset: True
  target_name: "MACE_ADO_EXTENDED_10y"
  zeroshot_prompt: True
  feature_config:
    feature_groups:
      - base_risk_score_inputs
      - additional_risk_score_inputs_aha_acc
      - additional_risk_score_inputs_prevent
model:
  type: huggingface
  name: "google/gemma-2-9b-it"
  precision: "16b"
  resume_training: false
training:
  eval_batch_size: 32
  optimizer:
    type: adamw
    lr: 0.0001
  scheduler:
    type: step
    step_size: 10000
    gamma: 0.9
