data:
  base_prompt_parts_file: prompt_parts.parquet
  data_dir: ukb_2024_02
  data_file: ukb677731.csv
  dataset_name: all_feature_groups
  feature_field_ids:
    - "30720"
    - "6150"
    - "6151"
    - "21000"
    - "21001"
    - "6152"
    - "21003"
    - "6153"
    - "6154"
    - "6155"
    - "30730"
    - "22032"
    - "22033"
    - "6162"
    - "22034"
    - "30740"
    - "6164"
    - "22035"
    - "22036"
    - "22037"
    - "22038"
    - "22039"
    - "1558"
    - "21021"
    - "30750"
    - "31"
    - "1568"
    - "6177"
    - "6179"
    - "30760"
    - "1578"
    - "3627"
    - "1070"
    - "30770"
    - "3063"
    - "1588"
    - "3637"
    - "1080"
    - "23098"
    - "23099"
    - "30780"
    - "23100"
    - "1598"
    - "3647"
    - "2624"
    - "23101"
    - "1090"
    - "23102"
    - "4674"
    - "30790"
    - "1608"
    - "2634"
    - "1618"
    - "2644"
    - "26202"
    - "30810"
    - "10844"
    - "93"
    - "26204"
    - "26206"
    - "1628"
    - "26210"
    - "4194"
    - "26212"
    - "4195"
    - "26214"
    - "4196"
    - "26216"
    - "4198"
    - "26218"
    - "4199"
    - "26220"
    - "4717"
    - "4200"
    - "26223"
    - "4204"
    - "26225"
    - "4207"
    - "26227"
    - "26229"
    - "26232"
    - "30840"
    - "26234"
    - "26238"
    - "26240"
    - "26242"
    - "2178"
    - "26244"
    - "26246"
    - "26248"
    - "1160"
    - "26250"
    - "20107"
    - "26252"
    - "2188"
    - "26254"
    - "30860"
    - "20110"
    - "20111"
    - "26258"
    - "20112"
    - "20116"
    - "26260"
    - "30870"
    - "20113"
    - "20114"
    - "26265"
    - "20117"
    - "26267"
    - "3731"
    - "26269"
    - "670"
    - "20119"
    - "30880"
    - "26273"
    - "26275"
    - "26278"
    - "1190"
    - "30890"
    - "26283"
    - "26284"
    - "26285"
    - "26286"
    - "26287"
    - "1200"
    - "26289"
    - "3761"
    - "20150"
    - "20151"
    - "1210"
    - "20160"
    - "20161"
    - "20162"
    - "1220"
    - "709"
    - "3786"
    - "1239"
    - "728"
    - "3809"
    - "1249"
    - "738"
    - "1259"
    - "1269"
    - "2296"
    - "1279"
    - "767"
    - "2306"
    - "777"
    - "2316"
    - "5901"
    - "1807"
    - "2844"
    - "796"
    - "20256"
    - "20257"
    - "20258"
    - "30500"
    - "806"
    - "2345"
    - "30505"
    - "30510"
    - "30000"
    - "816"
    - "2355"
    - "2867"
    - "1845"
    - "3894"
    - "30520"
    - "30010"
    - "826"
    - "2365"
    - "30525"
    - "30530"
    - "30020"
    - "2887"
    - "5959"
    - "30535"
    - "845"
    - "30030"
    - "2897"
    - "30040"
    - "2907"
    - "5983"
    - "864"
    - "30050"
    - "3426"
    - "874"
    - "30060"
    - "3436"
    - "2926"
    - "2415"
    - "884"
    - "30070"
    - "894"
    - "6015"
    - "30080"
    - "3456"
    - "6016"
    - "6017"
    - "30600"
    - "904"
    - "30090"
    - "2443"
    - "3466"
    - "6032"
    - "6033"
    - "30610"
    - "914"
    - "30100"
    - "2453"
    - "2966"
    - "4501"
    - "3992"
    - "6034"
    - "6039"
    - "30620"
    - "924"
    - "30110"
    - "2463"
    - "2976"
    - "30630"
    - "30120"
    - "2473"
    - "4012"
    - "943"
    - "30640"
    - "30130"
    - "3506"
    - "4022"
    - "30650"
    - "2492"
    - "3005"
    - "30140"
    - "30660"
    - "30150"
    - "3526"
    - "4041"
    - "971"
    - "30670"
    - "30160"
    - "981"
    - "4056"
    - "30680"
    - "23000"
    - "991"
    - "30690"
    - "1001"
    - "30700"
    - "4080"
    - "1011"
    - "30710"
    - "3062"
    - "3064"
    - "6138"
    - "1021"
    - "6143"
  features:
    - highest_qualification
    - BP_medication
    - ICD_10
    - Diabetes_medication
    - Cholesterol_medication
    - ICD_9
    - eGFR
  follow_up_years: 10
  target: MACE_ADO
