data:
  feature_config:
    feature_groups:
      #       # BASE RISK FACTORS
      - [base_risk_score_inputs]
      #       # - [base_risk_score_inputs, additional_risk_score_inputs_aha_acc]
      #       # - [base_risk_score_inputs, additional_risk_score_inputs_prevent]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
        ]
      #       # SEPARATE GROUPS
      # #       - [diabetes]
      # - [polygenic_risk_scores_all]
      # - [medical_history_all]
      # - [blood_samples]
      # - [icd_codes]
      # - [family_history]
      # - [physical_activity]
      # #       - [sleep, smoking, alcohol]
      # #       # - [smoking]
      # #       # - [alcohol]
      # - [lifestyle_and_environment]
      # - [physical_measures]
      # - [sociodemographics]
      # - [urine_assays]
      #       # BASE + X
      #       # - [
      #       #     base_risk_score_inputs,
      #       #     additional_risk_score_inputs_aha_acc,
      #       #     additional_risk_score_inputs_prevent,
      #       #     diabetes,
      #       #   ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          polygenic_risk_scores_all,
        ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          medical_history_all,
        ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          blood_samples,
        ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          icd_codes,
        ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          family_history,
        ]
      # - [
      #     base_risk_score_inputs,
      #     additional_risk_score_inputs_aha_acc,
      #     additional_risk_score_inputs_prevent,
      #     physical_activity,
      #   ]
      # - [
      #     base_risk_score_inputs,
      #     additional_risk_score_inputs_aha_acc,
      #     additional_risk_score_inputs_prevent,
      #     sleep,
      #   ]
      # - [
      #     base_risk_score_inputs,
      #     additional_risk_score_inputs_aha_acc,
      #     additional_risk_score_inputs_prevent,
      #     smoking,
      #   ]
      # - [
      #     base_risk_score_inputs,
      #     additional_risk_score_inputs_aha_acc,
      #     additional_risk_score_inputs_prevent,
      #     alcohol,
      #   ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          lifestyle_and_environment,
        ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          physical_measures,
        ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          sociodemographics,
        ]
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          urine_assays,
        ]
      #       # Base + X (larger lifestyle group)
      #       - [
      #           base_risk_score_inputs,
      #           additional_risk_score_inputs_aha_acc,
      #           additional_risk_score_inputs_prevent,
      #           smoking,
      #           sleep,
      #           alcohol,
      #         ]
      #       - [
      #           base_risk_score_inputs,
      #           additional_risk_score_inputs_aha_acc,
      #           additional_risk_score_inputs_prevent,
      #           physical_activity,
      #           smoking,
      #           sleep,
      #           alcohol,
      #         ]
      #       # COMBINATIONS of 2
      # # # - [
      # # #     base_risk_score_inputs,
      # # #     additional_risk_score_inputs_aha_acc,
      # # #     additional_risk_score_inputs_prevent,
      # # #     lifestyle_and_environment,
      # # #     medical_history_all,
      # # #   ]
      # # # - [
      # # #     base_risk_score_inputs,
      # # #     additional_risk_score_inputs_aha_acc,
      # # #     additional_risk_score_inputs_prevent,
      # # #     lifestyle_and_environment,
      # # #     family_history,
      # # #   ]
      # # # - [
      # # #     base_risk_score_inputs,
      # # #     additional_risk_score_inputs_aha_acc,
      # # #     additional_risk_score_inputs_prevent,
      # # #     lifestyle_and_environment,
      # # #     polygenic_risk_scores_all, # maybe use subset only
      # # #   ]
      # # # - [
      # # #     base_risk_score_inputs,
      # # #     additional_risk_score_inputs_aha_acc,
      # # #     additional_risk_score_inputs_prevent,
      # # #     medical_history_all,
      # # #     icd_codes,
      # # #   ]

      # # # #       # ARBITRARY COMBINATIONS
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     medical_history_all,
      # # # #       #     family_history,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     family_history,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     medical_history_all,
      # # # #       #     physical_activity,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #     physical_activity,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #     family_history,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #     family_history,
      # # # #       #     physical_activity,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #     family_history,
      # # # #       #     diabetes,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #     family_history,
      # # # #       #     diabetes,
      # # # #       #     physical_activity,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #     family_history,
      # # # #       #     lifestyle_and_environment,
      # # # #       #   ]
      # # # #       # - [
      # # # #       #     base_risk_score_inputs,
      # # # #       #     additional_risk_score_inputs_aha_acc,
      # # # #       #     additional_risk_score_inputs_prevent,
      # # # #       #     polygenic_risk_scores_all,
      # # # #       #     medical_history_all,
      # # # #       #     family_history,
      # # # #       #     lifestyle_and_environment,
      # # # #       #     physical_activity,
      # # # #       #   ]
      # # # # relevant combinations (based on LGBM results)
      # # # - [
      # # #     base_risk_score_inputs,
      # # #     additional_risk_score_inputs_aha_acc,
      # # #     additional_risk_score_inputs_prevent,
      # # #     polygenic_risk_scores_all,
      # # #     medical_history_all,
      # # #     icd_codes,
      # # #     family_history,
      # # #     lifestyle_and_environment,
      # # #     physical_measures,
      # # #     sociodemographics,
      # # #   ]
      # # # - [
      # # #     base_risk_score_inputs,
      # # #     additional_risk_score_inputs_aha_acc,
      # # #     additional_risk_score_inputs_prevent,
      # # #     polygenic_risk_scores_all,
      # # #     medical_history_all,
      # # #     blood_samples,
      # # #   ]
      # # # - [
      # # #     base_risk_score_inputs,
      # # #     additional_risk_score_inputs_aha_acc,
      # # #     additional_risk_score_inputs_prevent,
      # # #     polygenic_risk_scores_all,
      # # #     medical_history_all,
      # # #     blood_samples,
      # # #     lifestyle_and_environment,
      # # #   ]
      # all features
      - [
          base_risk_score_inputs,
          additional_risk_score_inputs_aha_acc,
          additional_risk_score_inputs_prevent,
          polygenic_risk_scores_all,
          medical_history_all,
          blood_samples,
          icd_codes,
          family_history,
          lifestyle_and_environment,
          physical_measures,
          sociodemographics,
          urine_assays,
        ]
